# Generated by Django 4.2.13 on 2024-05-16 23:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_id",
                    models.CharField(help_text="Unique identifier for the Stripe object", max_length=255, unique=True),
                ),
                ("data", models.JSONField(default=dict, help_text="Full JSON data from the Stripe object")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time when the object was first created in the database"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The time when the object was last updated in the database"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
