# Generated by Django 4.2.13 on 2024-05-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0002_charge_connect_account_id_charge_livemode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charge",
            options={},
        ),
    ]
