# Generated by Django 4.2.13 on 2024-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_intent", "0002_paymentintent_connect_account_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentintent",
            options={},
        ),
    ]
