# Generated by Django 4.2.13 on 2024-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_connect_account_id_account_livemode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
    ]
