# Generated by Django 4.2.13 on 2024-05-20 02:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_id",
                    models.CharField(help_text="Unique identifier for the Stripe object", max_length=255, unique=True),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False, help_text="Whether the object was created in live mode or test mode"
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Full JSON data from the Stripe object")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time when the object was first created in the database"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The time when the object was last updated in the database"
                    ),
                ),
                (
                    "connect_account_id",
                    models.CharField(
                        blank=True,
                        help_text="The account_id that this object is on behalf of(Stripe Connect only",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_id",
                    models.CharField(help_text="Unique identifier for the Stripe object", max_length=255, unique=True),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False, help_text="Whether the object was created in live mode or test mode"
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Full JSON data from the Stripe object")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time when the object was first created in the database"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The time when the object was last updated in the database"
                    ),
                ),
                (
                    "connect_account_id",
                    models.CharField(
                        blank=True,
                        help_text="The account_id that this object is on behalf of(Stripe Connect only",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_id",
                    models.CharField(help_text="Unique identifier for the Stripe object", max_length=255, unique=True),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False, help_text="Whether the object was created in live mode or test mode"
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Full JSON data from the Stripe object")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time when the object was first created in the database"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The time when the object was last updated in the database"
                    ),
                ),
                (
                    "connect_account_id",
                    models.CharField(
                        blank=True,
                        help_text="The account_id that this object is on behalf of(Stripe Connect only",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_id",
                    models.CharField(help_text="Unique identifier for the Stripe object", max_length=255, unique=True),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=False, help_text="Whether the object was created in live mode or test mode"
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Full JSON data from the Stripe object")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time when the object was first created in the database"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The time when the object was last updated in the database"
                    ),
                ),
                (
                    "connect_account_id",
                    models.CharField(
                        blank=True,
                        help_text="The account_id that this object is on behalf of(Stripe Connect only",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
